# Generated by Django 2.1.7 on 2021-03-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210322_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='1439536495-1.png', upload_to='profile_pics'),
        ),
    ]
