# Generated by Django 2.1.7 on 2021-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210322_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/1439536495-1.png', upload_to='profile_pics'),
        ),
    ]
